name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download dependencies
        run: |
          npm install
      - name: Compile TypeScript
        run: |
          ./node_modules/typescript/bin/tsc
      - name: Publish to npm
        run: |
          echo registry=https://registry.npmjs.org/ >> .npmrc
          echo _auth=${{ secrets.NPM_TOKEN }} >> .npmrc
          echo email=andrew.yakovenko@videogorillas.com >> .npmrc
          echo always-auth=true >> .npmrc
          npm config set registry https://registry.npmjs.org/
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
